/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import application.Main;
import java.util.List;
import classes.Grupos;
import classes.Produtos;
import controller.GruposDAO;
import controller.ProdutosDAO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import reportclasses.RelProdutos;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import util.CaixaDeDialogo;
import util.Uses;

/**
 *
 * @author Dionatan
 */
public class formRelProdutos extends javax.swing.JInternalFrame {
    private static CaixaDeDialogo mensagem;
    static int openFrameCount = 0;  
     private List<Grupos> gruposCadastrados = null;
    /**
     * Creates new form formRelProdutos
     */
    public formRelProdutos() {
        super("IFrame #" + (++openFrameCount),
                false, // resizable
                true, // closable
                false, // maximizable
                false);// iconifiable
        
        initComponents();
        Uses.center(this);
        carregaComboBoxGrupos();
        
        mensagem = CaixaDeDialogo.obterInstancia();
    }
    
    /**
     * Carrega dados de Grupos para o JCombobox
     */
    private void carregaComboBoxGrupos(){
        String sql = "FROM Grupos where grempresa = "+ String.valueOf(Main.empresaSelecionada.getEmcodigo());
        GruposDAO gruposDAO = new GruposDAO();
        
        try {
            List<Grupos> listGrupos = gruposDAO.consultaSQL(sql);           
                        
            gruposCadastrados = new ArrayList<>();
            cbGrupos.removeAllItems();
            cbGrupos.addItem("Todos");                
            for (int i = 0; i < listGrupos.size(); i++){
                Grupos grupo = listGrupos.get(i);
                
                gruposCadastrados.add(grupo);
                cbGrupos.addItem(grupo.getGrnome());                
            }                       
        } catch (Exception ex) {
            Logger.getLogger(formProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGeraRelatorio = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cbGrupos = new javax.swing.JComboBox();

        setTitle("Relatório de Produtos");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Filtros de Produtos");

        btnGeraRelatorio.setText("Gerar Relatório");
        btnGeraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraRelatorioActionPerformed(evt);
            }
        });

        jLabel24.setText("Grupo");

        cbGrupos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGeraRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(112, 112, 112)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGrupos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnGeraRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraRelatorioActionPerformed
                         
        String vSQL = "FROM Produtos where prcodigo is not null ";                
        
        if (cbGrupos.getSelectedIndex() > 0){
            vSQL = vSQL + " and prgrupo = "+ String.valueOf(gruposCadastrados.get(cbGrupos.getSelectedIndex()).getId().getGrcodigo());
        }
        
        vSQL = vSQL + " ORDER BY prnome";
        GruposDAO gruposDAO         = new GruposDAO();
        ProdutosDAO produtosDAO     = new ProdutosDAO();
        List<Produtos> listProdutos = produtosDAO.consultaSQL(vSQL);
        List<RelProdutos> listRel   = new ArrayList<RelProdutos>();
        
        for (int i = 0; i < listProdutos.size() ; i++){                    
            Grupos grupo = gruposDAO.getGrupo(Main.empresaSelecionada.getEmcodigo(), listProdutos.get(i).getPrgrupo());
            
            RelProdutos rel = new RelProdutos();
            
            rel.setEmcodigo(Main.empresaSelecionada.getEmcodigo());
            rel.setEmrazaosocial(Main.empresaSelecionada.getEmrazaosocial());
            rel.setEmfantasia(Main.empresaSelecionada.getEmfantasia());
            rel.setEmcidade(Main.empresaSelecionada.getEmcidade());
            rel.setEmbairro(Main.empresaSelecionada.getEmbairro());
            rel.setEmcnpj(Main.empresaSelecionada.getEmcnpj());
            rel.setEmuf(Main.empresaSelecionada.getEmuf());
            rel.setEmcep(Main.empresaSelecionada.getEmcep());
            
            rel.setPrcodigo(listProdutos.get(i).getId().getPrcodigo());
            rel.setPrnome(listProdutos.get(i).getPrnome());
            rel.setPrunidade(listProdutos.get(i).getPrunidade());
            rel.setGrnome(grupo.getGrnome());
                               
            listRel.add(rel);
        }                        
        JasperPrint jpPrint = null;
        try {
            jpPrint = JasperFillManager.fillReport("iReport/RelatorioProdutosNovo.jasper", new HashMap(), new JRBeanCollectionDataSource(listRel));
            JasperViewer jpViewer = new JasperViewer(jpPrint , false); //false - não encerra a aplicação ao fechar a janela                       
            jpViewer.setVisible(true);
            jpViewer.toFront(); //apresenta o relatório acima das outras janelas            
            jpViewer.setAlwaysOnTop(true);            
        } catch (JRException ex) {
            Logger.getLogger(formRelClientes.class.getName()).log(Level.SEVERE, null, ex);
        }           
    }//GEN-LAST:event_btnGeraRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeraRelatorio;
    private javax.swing.JComboBox cbGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    // End of variables declaration//GEN-END:variables
}
