/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import application.Main;
import java.util.Vector;
import javax.swing.JTextField;
import util.Uses;

/**
 *
 * @author Dionatan
 */
public class formPesquisa extends javax.swing.JInternalFrame {

    /**
     * Creates new form formPesquisa
     */
    private static Vector<String> camposPesq = null;
    private static Vector<String> cabecalhoPesq = null;
    private static String vSQL = null;
    static int openFrameCount = 0;
    private JTextField edtReturn;
    private Class classe;
    
    public formPesquisa(JTextField jtf, String SQL, Class cl ){
      
        super("IFrame #" + (++openFrameCount),
             false, // resizable
             true, // closable
             false, // maximizable
             true);// iconifiable}
         
        edtReturn = jtf;
        vSQL      = SQL;
        classe    = cl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbCampos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BotaoConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridPesquisar = new javax.swing.JTable();
        BotaoConsulta1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridPesquisar1 = new javax.swing.JTable();

        setTitle("Pesquisar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setTitle("Pesquisa de Dados");

        jLabel1.setText("Campo");

        jLabel2.setText("Consulta");

        BotaoConsulta.setText("Consultar");
        BotaoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotaoConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(BotaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridPesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        gridPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridPesquisarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridPesquisar);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 105, 0, 0));

        BotaoConsulta1.setText("Consultar");
        BotaoConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsulta1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 143, 44));

        gridPesquisar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        gridPesquisar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridPesquisar1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gridPesquisar1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 480, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void BotaoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultaActionPerformed
        Uses.popularTabela(gridPesquisar, vSQL, classe);
    }//GEN-LAST:event_BotaoConsultaActionPerformed

    private void gridPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridPesquisarMouseClicked
        if (evt.getClickCount() == 2){
            int row = gridPesquisar.getSelectedRow();

            if (row < 0)
            {
                return;
            } else
            {
                Main.vValorPesquisa = gridPesquisar.getValueAt(row, 0).toString();
                edtReturn.setText(Main.vValorPesquisa);
                edtReturn.grabFocus();
                dispose();
            }
        }
    }//GEN-LAST:event_gridPesquisarMouseClicked

    private void BotaoConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsulta1ActionPerformed
         Uses.popularTabela(gridPesquisar1, vSQL, classe);
    }//GEN-LAST:event_BotaoConsulta1ActionPerformed

    private void gridPesquisar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridPesquisar1MouseClicked
        if (evt.getClickCount() == 2){
            int row = gridPesquisar1.getSelectedRow();
            if (row < 0){
                return;
            } else            {
                Main.vValorPesquisa = gridPesquisar1.getValueAt(row, 0).toString();
                edtReturn.setText(Main.vValorPesquisa);
                edtReturn.grabFocus();
                dispose();
            }
        }
    }//GEN-LAST:event_gridPesquisar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConsulta;
    private javax.swing.JButton BotaoConsulta1;
    private javax.swing.JComboBox cbCampos;
    private javax.swing.JTable gridPesquisar;
    private javax.swing.JTable gridPesquisar1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
