package classes;
// Generated 27/06/2017 20:29:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private ClientesId id;
     private Empresa empresa;
     private String clmatricula;
     private String clnome;
     private String clendereco;
     private String clcidade;
     private String clbairro;
     private String cluf;
     private String clcep;
     private String clfone;
     private String clemail;
     private String clcpf;
     private String clcnpj;
     private String clinativo;
     private Date cldataatu;
     private Date clhoraatu;

    public Clientes() {
    }

	
    public Clientes(ClientesId id, Empresa empresa, Date cldataatu, Date clhoraatu) {
        this.id = id;
        this.empresa = empresa;
        this.cldataatu = cldataatu;
        this.clhoraatu = clhoraatu;
    }
    public Clientes(ClientesId id, Empresa empresa, String clmatricula, String clnome, String clendereco, String clcidade, String clbairro, String cluf, String clcep, String clfone, String clemail, String clcpf, String clcnpj, String clinativo, Date cldataatu, Date clhoraatu) {
       this.id = id;
       this.empresa = empresa;
       this.clmatricula = clmatricula;
       this.clnome = clnome;
       this.clendereco = clendereco;
       this.clcidade = clcidade;
       this.clbairro = clbairro;
       this.cluf = cluf;
       this.clcep = clcep;
       this.clfone = clfone;
       this.clemail = clemail;
       this.clcpf = clcpf;
       this.clcnpj = clcnpj;
       this.clinativo = clinativo;
       this.cldataatu = cldataatu;
       this.clhoraatu = clhoraatu;
    }
   
    public ClientesId getId() {
        return this.id;
    }
    
    public void setId(ClientesId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getClmatricula() {
        return this.clmatricula;
    }
    
    public void setClmatricula(String clmatricula) {
        this.clmatricula = clmatricula;
    }
    public String getClnome() {
        return this.clnome;
    }
    
    public void setClnome(String clnome) {
        this.clnome = clnome;
    }
    public String getClendereco() {
        return this.clendereco;
    }
    
    public void setClendereco(String clendereco) {
        this.clendereco = clendereco;
    }
    public String getClcidade() {
        return this.clcidade;
    }
    
    public void setClcidade(String clcidade) {
        this.clcidade = clcidade;
    }
    public String getClbairro() {
        return this.clbairro;
    }
    
    public void setClbairro(String clbairro) {
        this.clbairro = clbairro;
    }
    public String getCluf() {
        return this.cluf;
    }
    
    public void setCluf(String cluf) {
        this.cluf = cluf;
    }
    public String getClcep() {
        return this.clcep;
    }
    
    public void setClcep(String clcep) {
        this.clcep = clcep;
    }
    public String getClfone() {
        return this.clfone;
    }
    
    public void setClfone(String clfone) {
        this.clfone = clfone;
    }
    public String getClemail() {
        return this.clemail;
    }
    
    public void setClemail(String clemail) {
        this.clemail = clemail;
    }
    public String getClcpf() {
        return this.clcpf;
    }
    
    public void setClcpf(String clcpf) {
        this.clcpf = clcpf;
    }
    public String getClcnpj() {
        return this.clcnpj;
    }
    
    public void setClcnpj(String clcnpj) {
        this.clcnpj = clcnpj;
    }
    public String getClinativo() {
        return this.clinativo;
    }
    
    public void setClinativo(String clinativo) {
        this.clinativo = clinativo;
    }
    public Date getCldataatu() {
        return this.cldataatu;
    }
    
    public void setCldataatu(Date cldataatu) {
        this.cldataatu = cldataatu;
    }
    public Date getClhoraatu() {
        return this.clhoraatu;
    }
    
    public void setClhoraatu(Date clhoraatu) {
        this.clhoraatu = clhoraatu;
    }




}


