package classes;
// Generated 24/06/2017 11:39:22 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientesId generated by hbm2java
 */
@Embeddable
public class ClientesId  implements java.io.Serializable {


     private int clempresa;
     private int clcodigo;

    public ClientesId() {
    }

    public ClientesId(int clempresa, int clcodigo) {
       this.clempresa = clempresa;
       this.clcodigo = clcodigo;
    }
   


    @Column(name="clempresa", nullable=false)
    public int getClempresa() {
        return this.clempresa;
    }
    
    public void setClempresa(int clempresa) {
        this.clempresa = clempresa;
    }


    @Column(name="clcodigo", nullable=false)
    public int getClcodigo() {
        return this.clcodigo;
    }
    
    public void setClcodigo(int clcodigo) {
        this.clcodigo = clcodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientesId) ) return false;
		 ClientesId castOther = ( ClientesId ) other; 
         
		 return (this.getClempresa()==castOther.getClempresa())
 && (this.getClcodigo()==castOther.getClcodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClempresa();
         result = 37 * result + this.getClcodigo();
         return result;
   }   


}


