package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,schema="public"
)
public class Empresa  implements java.io.Serializable {


     private int emcodigo;
     private String emrazaosocial;
     private String emfantasia;
     private String emcnpj;
     private String emcep;
     private String emuf;
     private String embairro;
     private String emcidade;
     private String emendereco;
     private String ememail;
     private String emtelefone;
     private Date emdataatu;
     private Date emhoraatu;
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);
     private Set<Grupos> gruposes = new HashSet<Grupos>(0);
     private Set<Formaspgto> formaspgtos = new HashSet<Formaspgto>(0);
     private Set<Tabelaprecos> tabelaprecoses = new HashSet<Tabelaprecos>(0);
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Empresa() {
    }

	
    public Empresa(int emcodigo, String emcnpj, String emcep) {
        this.emcodigo = emcodigo;
        this.emcnpj = emcnpj;
        this.emcep = emcep;
    }
    public Empresa(int emcodigo, String emrazaosocial, String emfantasia, String emcnpj, String emcep, String emuf, String embairro, String emcidade, String emendereco, String ememail, String emtelefone, Date emdataatu, Date emhoraatu, Set<Produtos> produtoses, Set<Grupos> gruposes, Set<Formaspgto> formaspgtos, Set<Tabelaprecos> tabelaprecoses, Set<Clientes> clienteses, Set<Pedidos> pedidoses, Set<Usuario> usuarios) {
       this.emcodigo = emcodigo;
       this.emrazaosocial = emrazaosocial;
       this.emfantasia = emfantasia;
       this.emcnpj = emcnpj;
       this.emcep = emcep;
       this.emuf = emuf;
       this.embairro = embairro;
       this.emcidade = emcidade;
       this.emendereco = emendereco;
       this.ememail = ememail;
       this.emtelefone = emtelefone;
       this.emdataatu = emdataatu;
       this.emhoraatu = emhoraatu;
       this.produtoses = produtoses;
       this.gruposes = gruposes;
       this.formaspgtos = formaspgtos;
       this.tabelaprecoses = tabelaprecoses;
       this.clienteses = clienteses;
       this.pedidoses = pedidoses;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="emcodigo", unique=true, nullable=false)
    public int getEmcodigo() {
        return this.emcodigo;
    }
    
    public void setEmcodigo(int emcodigo) {
        this.emcodigo = emcodigo;
    }

    
    @Column(name="emrazaosocial", length=100)
    public String getEmrazaosocial() {
        return this.emrazaosocial;
    }
    
    public void setEmrazaosocial(String emrazaosocial) {
        this.emrazaosocial = emrazaosocial;
    }

    
    @Column(name="emfantasia", length=100)
    public String getEmfantasia() {
        return this.emfantasia;
    }
    
    public void setEmfantasia(String emfantasia) {
        this.emfantasia = emfantasia;
    }

    
    @Column(name="emcnpj", nullable=false, length=14)
    public String getEmcnpj() {
        return this.emcnpj;
    }
    
    public void setEmcnpj(String emcnpj) {
        this.emcnpj = emcnpj;
    }

    
    @Column(name="emcep", nullable=false, length=9)
    public String getEmcep() {
        return this.emcep;
    }
    
    public void setEmcep(String emcep) {
        this.emcep = emcep;
    }

    
    @Column(name="emuf", length=2)
    public String getEmuf() {
        return this.emuf;
    }
    
    public void setEmuf(String emuf) {
        this.emuf = emuf;
    }

    
    @Column(name="embairro", length=30)
    public String getEmbairro() {
        return this.embairro;
    }
    
    public void setEmbairro(String embairro) {
        this.embairro = embairro;
    }

    
    @Column(name="emcidade", length=50)
    public String getEmcidade() {
        return this.emcidade;
    }
    
    public void setEmcidade(String emcidade) {
        this.emcidade = emcidade;
    }

    
    @Column(name="emendereco", length=100)
    public String getEmendereco() {
        return this.emendereco;
    }
    
    public void setEmendereco(String emendereco) {
        this.emendereco = emendereco;
    }

    
    @Column(name="ememail", length=50)
    public String getEmemail() {
        return this.ememail;
    }
    
    public void setEmemail(String ememail) {
        this.ememail = ememail;
    }

    
    @Column(name="emtelefone", length=20)
    public String getEmtelefone() {
        return this.emtelefone;
    }
    
    public void setEmtelefone(String emtelefone) {
        this.emtelefone = emtelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="emdataatu", length=13)
    public Date getEmdataatu() {
        return this.emdataatu;
    }
    
    public void setEmdataatu(Date emdataatu) {
        this.emdataatu = emdataatu;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="emhoraatu", length=15)
    public Date getEmhoraatu() {
        return this.emhoraatu;
    }
    
    public void setEmhoraatu(Date emhoraatu) {
        this.emhoraatu = emhoraatu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Grupos> getGruposes() {
        return this.gruposes;
    }
    
    public void setGruposes(Set<Grupos> gruposes) {
        this.gruposes = gruposes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Formaspgto> getFormaspgtos() {
        return this.formaspgtos;
    }
    
    public void setFormaspgtos(Set<Formaspgto> formaspgtos) {
        this.formaspgtos = formaspgtos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Tabelaprecos> getTabelaprecoses() {
        return this.tabelaprecoses;
    }
    
    public void setTabelaprecoses(Set<Tabelaprecos> tabelaprecoses) {
        this.tabelaprecoses = tabelaprecoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


