package classes;
// Generated 24/06/2017 11:39:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Formaspgto generated by hbm2java
 */
@Entity
@Table(name="formaspgto"
    ,schema="public"
)
public class Formaspgto  implements java.io.Serializable {


     private FormaspgtoId id;
     private Empresa empresa;
     private String fpdescricao;
     private Integer fpnrovezes;
     private Date fpdataatu;
     private Date fphoraatu;
     private Set pedidoses = new HashSet(0);

    public Formaspgto() {
    }

	
    public Formaspgto(FormaspgtoId id, Empresa empresa) {
        this.id = id;
        this.empresa = empresa;
    }
    public Formaspgto(FormaspgtoId id, Empresa empresa, String fpdescricao, Integer fpnrovezes, Date fpdataatu, Date fphoraatu, Set pedidoses) {
       this.id = id;
       this.empresa = empresa;
       this.fpdescricao = fpdescricao;
       this.fpnrovezes = fpnrovezes;
       this.fpdataatu = fpdataatu;
       this.fphoraatu = fphoraatu;
       this.pedidoses = pedidoses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fpempresa", column=@Column(name="fpempresa", nullable=false) ), 
        @AttributeOverride(name="fpcodigo", column=@Column(name="fpcodigo", nullable=false) ) } )
    public FormaspgtoId getId() {
        return this.id;
    }
    
    public void setId(FormaspgtoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fpempresa", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="fpdescricao", length=100)
    public String getFpdescricao() {
        return this.fpdescricao;
    }
    
    public void setFpdescricao(String fpdescricao) {
        this.fpdescricao = fpdescricao;
    }

    
    @Column(name="fpnrovezes")
    public Integer getFpnrovezes() {
        return this.fpnrovezes;
    }
    
    public void setFpnrovezes(Integer fpnrovezes) {
        this.fpnrovezes = fpnrovezes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fpdataatu", length=13)
    public Date getFpdataatu() {
        return this.fpdataatu;
    }
    
    public void setFpdataatu(Date fpdataatu) {
        this.fpdataatu = fpdataatu;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="fphoraatu", length=15)
    public Date getFphoraatu() {
        return this.fphoraatu;
    }
    
    public void setFphoraatu(Date fphoraatu) {
        this.fphoraatu = fphoraatu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formaspgto")
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


