package classes;
// Generated 06/07/2017 22:21:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Formaspgto generated by hbm2java
 */
public class Formaspgto  implements java.io.Serializable {


     private FormaspgtoId id;
     private Empresa empresa;
     private String fpdescricao;
     private Integer fpnrovezes;
     private Date fpdataatu;
     private Date fphoraatu;

    public Formaspgto() {
    }

	
    public Formaspgto(FormaspgtoId id, Empresa empresa) {
        this.id = id;
        this.empresa = empresa;
    }
    public Formaspgto(FormaspgtoId id, Empresa empresa, String fpdescricao, Integer fpnrovezes, Date fpdataatu, Date fphoraatu) {
       this.id = id;
       this.empresa = empresa;
       this.fpdescricao = fpdescricao;
       this.fpnrovezes = fpnrovezes;
       this.fpdataatu = fpdataatu;
       this.fphoraatu = fphoraatu;
    }
   
    public FormaspgtoId getId() {
        return this.id;
    }
    
    public void setId(FormaspgtoId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getFpdescricao() {
        return this.fpdescricao;
    }
    
    public void setFpdescricao(String fpdescricao) {
        this.fpdescricao = fpdescricao;
    }
    public Integer getFpnrovezes() {
        return this.fpnrovezes;
    }
    
    public void setFpnrovezes(Integer fpnrovezes) {
        this.fpnrovezes = fpnrovezes;
    }
    public Date getFpdataatu() {
        return this.fpdataatu;
    }
    
    public void setFpdataatu(Date fpdataatu) {
        this.fpdataatu = fpdataatu;
    }
    public Date getFphoraatu() {
        return this.fphoraatu;
    }
    
    public void setFphoraatu(Date fphoraatu) {
        this.fphoraatu = fphoraatu;
    }




}


