package classes;
// Generated 06/07/2017 22:21:10 by Hibernate Tools 4.3.1



/**
 * FormaspgtoId generated by hbm2java
 */
public class FormaspgtoId  implements java.io.Serializable {


     private int fpempresa;
     private int fpcodigo;

    public FormaspgtoId() {
    }

    public FormaspgtoId(int fpempresa, int fpcodigo) {
       this.fpempresa = fpempresa;
       this.fpcodigo = fpcodigo;
    }
   
    public int getFpempresa() {
        return this.fpempresa;
    }
    
    public void setFpempresa(int fpempresa) {
        this.fpempresa = fpempresa;
    }
    public int getFpcodigo() {
        return this.fpcodigo;
    }
    
    public void setFpcodigo(int fpcodigo) {
        this.fpcodigo = fpcodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormaspgtoId) ) return false;
		 FormaspgtoId castOther = ( FormaspgtoId ) other; 
         
		 return (this.getFpempresa()==castOther.getFpempresa())
 && (this.getFpcodigo()==castOther.getFpcodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFpempresa();
         result = 37 * result + this.getFpcodigo();
         return result;
   }   


}


