package classes;
// Generated 24/06/2017 11:39:22 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name="grupos"
    ,schema="public"
)
public class Grupos  implements java.io.Serializable {


     private GruposId id;
     private Empresa empresa;
     private String grnome;
     private Date grdataatu;
     private Date grhoraatu;

    public Grupos() {
    }

	
    public Grupos(GruposId id, Empresa empresa, Date grdataatu, Date grhoraatu) {
        this.id = id;
        this.empresa = empresa;
        this.grdataatu = grdataatu;
        this.grhoraatu = grhoraatu;
    }
    public Grupos(GruposId id, Empresa empresa, String grnome, Date grdataatu, Date grhoraatu) {
       this.id = id;
       this.empresa = empresa;
       this.grnome = grnome;
       this.grdataatu = grdataatu;
       this.grhoraatu = grhoraatu;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="grempresa", column=@Column(name="grempresa", nullable=false) ), 
        @AttributeOverride(name="grcodigo", column=@Column(name="grcodigo", nullable=false) ) } )
    public GruposId getId() {
        return this.id;
    }
    
    public void setId(GruposId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grempresa", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="grnome", length=50)
    public String getGrnome() {
        return this.grnome;
    }
    
    public void setGrnome(String grnome) {
        this.grnome = grnome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="grdataatu", nullable=false, length=13)
    public Date getGrdataatu() {
        return this.grdataatu;
    }
    
    public void setGrdataatu(Date grdataatu) {
        this.grdataatu = grdataatu;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="grhoraatu", nullable=false, length=15)
    public Date getGrhoraatu() {
        return this.grhoraatu;
    }
    
    public void setGrhoraatu(Date grhoraatu) {
        this.grhoraatu = grhoraatu;
    }




}


