package classes;
// Generated 27/06/2017 20:29:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Itenspedido generated by hbm2java
 */
public class Itenspedido  implements java.io.Serializable {


     private ItenspedidoId id;
     private Pedidos pedidos;
     private int iptabelapreco;
     private BigDecimal ipquantidade;
     private BigDecimal ipvalorunit;
     private BigDecimal ipvalortotal;
     private BigDecimal ippercdesconto;
     private Date ipdataatu;
     private Date iphoraatu;
     private String ipobs;

    public Itenspedido() {
    }

	
    public Itenspedido(ItenspedidoId id, Pedidos pedidos, int iptabelapreco, BigDecimal ipquantidade, BigDecimal ipvalorunit, BigDecimal ipvalortotal, Date ipdataatu, Date iphoraatu) {
        this.id = id;
        this.pedidos = pedidos;
        this.iptabelapreco = iptabelapreco;
        this.ipquantidade = ipquantidade;
        this.ipvalorunit = ipvalorunit;
        this.ipvalortotal = ipvalortotal;
        this.ipdataatu = ipdataatu;
        this.iphoraatu = iphoraatu;
    }
    public Itenspedido(ItenspedidoId id, Pedidos pedidos, int iptabelapreco, BigDecimal ipquantidade, BigDecimal ipvalorunit, BigDecimal ipvalortotal, BigDecimal ippercdesconto, Date ipdataatu, Date iphoraatu, String ipobs) {
       this.id = id;
       this.pedidos = pedidos;
       this.iptabelapreco = iptabelapreco;
       this.ipquantidade = ipquantidade;
       this.ipvalorunit = ipvalorunit;
       this.ipvalortotal = ipvalortotal;
       this.ippercdesconto = ippercdesconto;
       this.ipdataatu = ipdataatu;
       this.iphoraatu = iphoraatu;
       this.ipobs = ipobs;
    }
   
    public ItenspedidoId getId() {
        return this.id;
    }
    
    public void setId(ItenspedidoId id) {
        this.id = id;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public int getIptabelapreco() {
        return this.iptabelapreco;
    }
    
    public void setIptabelapreco(int iptabelapreco) {
        this.iptabelapreco = iptabelapreco;
    }
    public BigDecimal getIpquantidade() {
        return this.ipquantidade;
    }
    
    public void setIpquantidade(BigDecimal ipquantidade) {
        this.ipquantidade = ipquantidade;
    }
    public BigDecimal getIpvalorunit() {
        return this.ipvalorunit;
    }
    
    public void setIpvalorunit(BigDecimal ipvalorunit) {
        this.ipvalorunit = ipvalorunit;
    }
    public BigDecimal getIpvalortotal() {
        return this.ipvalortotal;
    }
    
    public void setIpvalortotal(BigDecimal ipvalortotal) {
        this.ipvalortotal = ipvalortotal;
    }
    public BigDecimal getIppercdesconto() {
        return this.ippercdesconto;
    }
    
    public void setIppercdesconto(BigDecimal ippercdesconto) {
        this.ippercdesconto = ippercdesconto;
    }
    public Date getIpdataatu() {
        return this.ipdataatu;
    }
    
    public void setIpdataatu(Date ipdataatu) {
        this.ipdataatu = ipdataatu;
    }
    public Date getIphoraatu() {
        return this.iphoraatu;
    }
    
    public void setIphoraatu(Date iphoraatu) {
        this.iphoraatu = iphoraatu;
    }
    public String getIpobs() {
        return this.ipobs;
    }
    
    public void setIpobs(String ipobs) {
        this.ipobs = ipobs;
    }




}


