package classes;
// Generated 27/06/2017 20:29:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private PedidosId id;
     private Empresa empresa;
     private Usuario usuario;
     private int pecliente;
     private Integer peduracao;
     private BigDecimal peproducaoleite;
     private BigDecimal pepesovivo;
     private Integer penrolactantes;
     private Integer penropreparto;
     private Integer penronovilhas;
     private Integer penroterneiras2mes;
     private Integer penroterneiras6mes;
     private BigDecimal pevalortotal;
     private String peobs;
     private String pecancelado;
     private Date pedataatu;
     private Date pehoraatu;
     private Date pedata;
     private int peformapgto;
     private String pemotivocancelamento;
     private Set itenspedidos = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(PedidosId id, Empresa empresa, Usuario usuario, int pecliente, Date pedataatu, Date pehoraatu, int peformapgto) {
        this.id = id;
        this.empresa = empresa;
        this.usuario = usuario;
        this.pecliente = pecliente;
        this.pedataatu = pedataatu;
        this.pehoraatu = pehoraatu;
        this.peformapgto = peformapgto;
    }
    public Pedidos(PedidosId id, Empresa empresa, Usuario usuario, int pecliente, Integer peduracao, BigDecimal peproducaoleite, BigDecimal pepesovivo, Integer penrolactantes, Integer penropreparto, Integer penronovilhas, Integer penroterneiras2mes, Integer penroterneiras6mes, BigDecimal pevalortotal, String peobs, String pecancelado, Date pedataatu, Date pehoraatu, Date pedata, int peformapgto, String pemotivocancelamento, Set itenspedidos) {
       this.id = id;
       this.empresa = empresa;
       this.usuario = usuario;
       this.pecliente = pecliente;
       this.peduracao = peduracao;
       this.peproducaoleite = peproducaoleite;
       this.pepesovivo = pepesovivo;
       this.penrolactantes = penrolactantes;
       this.penropreparto = penropreparto;
       this.penronovilhas = penronovilhas;
       this.penroterneiras2mes = penroterneiras2mes;
       this.penroterneiras6mes = penroterneiras6mes;
       this.pevalortotal = pevalortotal;
       this.peobs = peobs;
       this.pecancelado = pecancelado;
       this.pedataatu = pedataatu;
       this.pehoraatu = pehoraatu;
       this.pedata = pedata;
       this.peformapgto = peformapgto;
       this.pemotivocancelamento = pemotivocancelamento;
       this.itenspedidos = itenspedidos;
    }
   
    public PedidosId getId() {
        return this.id;
    }
    
    public void setId(PedidosId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getPecliente() {
        return this.pecliente;
    }
    
    public void setPecliente(int pecliente) {
        this.pecliente = pecliente;
    }
    public Integer getPeduracao() {
        return this.peduracao;
    }
    
    public void setPeduracao(Integer peduracao) {
        this.peduracao = peduracao;
    }
    public BigDecimal getPeproducaoleite() {
        return this.peproducaoleite;
    }
    
    public void setPeproducaoleite(BigDecimal peproducaoleite) {
        this.peproducaoleite = peproducaoleite;
    }
    public BigDecimal getPepesovivo() {
        return this.pepesovivo;
    }
    
    public void setPepesovivo(BigDecimal pepesovivo) {
        this.pepesovivo = pepesovivo;
    }
    public Integer getPenrolactantes() {
        return this.penrolactantes;
    }
    
    public void setPenrolactantes(Integer penrolactantes) {
        this.penrolactantes = penrolactantes;
    }
    public Integer getPenropreparto() {
        return this.penropreparto;
    }
    
    public void setPenropreparto(Integer penropreparto) {
        this.penropreparto = penropreparto;
    }
    public Integer getPenronovilhas() {
        return this.penronovilhas;
    }
    
    public void setPenronovilhas(Integer penronovilhas) {
        this.penronovilhas = penronovilhas;
    }
    public Integer getPenroterneiras2mes() {
        return this.penroterneiras2mes;
    }
    
    public void setPenroterneiras2mes(Integer penroterneiras2mes) {
        this.penroterneiras2mes = penroterneiras2mes;
    }
    public Integer getPenroterneiras6mes() {
        return this.penroterneiras6mes;
    }
    
    public void setPenroterneiras6mes(Integer penroterneiras6mes) {
        this.penroterneiras6mes = penroterneiras6mes;
    }
    public BigDecimal getPevalortotal() {
        return this.pevalortotal;
    }
    
    public void setPevalortotal(BigDecimal pevalortotal) {
        this.pevalortotal = pevalortotal;
    }
    public String getPeobs() {
        return this.peobs;
    }
    
    public void setPeobs(String peobs) {
        this.peobs = peobs;
    }
    public String getPecancelado() {
        return this.pecancelado;
    }
    
    public void setPecancelado(String pecancelado) {
        this.pecancelado = pecancelado;
    }
    public Date getPedataatu() {
        return this.pedataatu;
    }
    
    public void setPedataatu(Date pedataatu) {
        this.pedataatu = pedataatu;
    }
    public Date getPehoraatu() {
        return this.pehoraatu;
    }
    
    public void setPehoraatu(Date pehoraatu) {
        this.pehoraatu = pehoraatu;
    }
    public Date getPedata() {
        return this.pedata;
    }
    
    public void setPedata(Date pedata) {
        this.pedata = pedata;
    }
    public int getPeformapgto() {
        return this.peformapgto;
    }
    
    public void setPeformapgto(int peformapgto) {
        this.peformapgto = peformapgto;
    }
    public String getPemotivocancelamento() {
        return this.pemotivocancelamento;
    }
    
    public void setPemotivocancelamento(String pemotivocancelamento) {
        this.pemotivocancelamento = pemotivocancelamento;
    }
    public Set getItenspedidos() {
        return this.itenspedidos;
    }
    
    public void setItenspedidos(Set itenspedidos) {
        this.itenspedidos = itenspedidos;
    }




}


