package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,schema="public"
)
public class Pedidos  implements java.io.Serializable {


     private PedidosId id;
     private Clientes clientes;
     private Empresa empresa;
     private Formaspgto formaspgto;
     private Usuario usuario;
     private Integer peduracao;
     private BigDecimal peproducaoleite;
     private BigDecimal pepesovivo;
     private Integer penrolactantes;
     private Integer penropreparto;
     private Integer penronovilhas;
     private Integer penroterneiras2mes;
     private Integer penroterneiras6mes;
     private BigDecimal pevalortotal;
     private String peobs;
     private String pecancelado;
     private Date pedataatu;
     private Date pehoraatu;
     private Date pedata;
     private String pemotivocancelamento;
     private Set<Itenspedido> itenspedidos = new HashSet<Itenspedido>(0);

    public Pedidos() {
    }

	
    public Pedidos(PedidosId id, Clientes clientes, Empresa empresa, Formaspgto formaspgto, Usuario usuario, Date pedataatu, Date pehoraatu) {
        this.id = id;
        this.clientes = clientes;
        this.empresa = empresa;
        this.formaspgto = formaspgto;
        this.usuario = usuario;
        this.pedataatu = pedataatu;
        this.pehoraatu = pehoraatu;
    }
    public Pedidos(PedidosId id, Clientes clientes, Empresa empresa, Formaspgto formaspgto, Usuario usuario, Integer peduracao, BigDecimal peproducaoleite, BigDecimal pepesovivo, Integer penrolactantes, Integer penropreparto, Integer penronovilhas, Integer penroterneiras2mes, Integer penroterneiras6mes, BigDecimal pevalortotal, String peobs, String pecancelado, Date pedataatu, Date pehoraatu, Date pedata, String pemotivocancelamento, Set<Itenspedido> itenspedidos) {
       this.id = id;
       this.clientes = clientes;
       this.empresa = empresa;
       this.formaspgto = formaspgto;
       this.usuario = usuario;
       this.peduracao = peduracao;
       this.peproducaoleite = peproducaoleite;
       this.pepesovivo = pepesovivo;
       this.penrolactantes = penrolactantes;
       this.penropreparto = penropreparto;
       this.penronovilhas = penronovilhas;
       this.penroterneiras2mes = penroterneiras2mes;
       this.penroterneiras6mes = penroterneiras6mes;
       this.pevalortotal = pevalortotal;
       this.peobs = peobs;
       this.pecancelado = pecancelado;
       this.pedataatu = pedataatu;
       this.pehoraatu = pehoraatu;
       this.pedata = pedata;
       this.pemotivocancelamento = pemotivocancelamento;
       this.itenspedidos = itenspedidos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="peusuario", column=@Column(name="peusuario", nullable=false) ), 
        @AttributeOverride(name="peempresa", column=@Column(name="peempresa", nullable=false) ), 
        @AttributeOverride(name="pepedido", column=@Column(name="pepedido", nullable=false) ) } )
    public PedidosId getId() {
        return this.id;
    }
    
    public void setId(PedidosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="pecliente", referencedColumnName="clempresa", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="peempresa", referencedColumnName="clcodigo", nullable=false, insertable=false, updatable=false) } )
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="peempresa", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="peformapgto", referencedColumnName="fpempresa", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="peempresa", referencedColumnName="fpcodigo", nullable=false, insertable=false, updatable=false) } )
    public Formaspgto getFormaspgto() {
        return this.formaspgto;
    }
    
    public void setFormaspgto(Formaspgto formaspgto) {
        this.formaspgto = formaspgto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="peusuario", referencedColumnName="uscodigo", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="peempresa", referencedColumnName="usempresa", nullable=false, insertable=false, updatable=false) } )
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="peduracao")
    public Integer getPeduracao() {
        return this.peduracao;
    }
    
    public void setPeduracao(Integer peduracao) {
        this.peduracao = peduracao;
    }

    
    @Column(name="peproducaoleite", precision=15)
    public BigDecimal getPeproducaoleite() {
        return this.peproducaoleite;
    }
    
    public void setPeproducaoleite(BigDecimal peproducaoleite) {
        this.peproducaoleite = peproducaoleite;
    }

    
    @Column(name="pepesovivo", precision=15)
    public BigDecimal getPepesovivo() {
        return this.pepesovivo;
    }
    
    public void setPepesovivo(BigDecimal pepesovivo) {
        this.pepesovivo = pepesovivo;
    }

    
    @Column(name="penrolactantes")
    public Integer getPenrolactantes() {
        return this.penrolactantes;
    }
    
    public void setPenrolactantes(Integer penrolactantes) {
        this.penrolactantes = penrolactantes;
    }

    
    @Column(name="penropreparto")
    public Integer getPenropreparto() {
        return this.penropreparto;
    }
    
    public void setPenropreparto(Integer penropreparto) {
        this.penropreparto = penropreparto;
    }

    
    @Column(name="penronovilhas")
    public Integer getPenronovilhas() {
        return this.penronovilhas;
    }
    
    public void setPenronovilhas(Integer penronovilhas) {
        this.penronovilhas = penronovilhas;
    }

    
    @Column(name="penroterneiras2mes")
    public Integer getPenroterneiras2mes() {
        return this.penroterneiras2mes;
    }
    
    public void setPenroterneiras2mes(Integer penroterneiras2mes) {
        this.penroterneiras2mes = penroterneiras2mes;
    }

    
    @Column(name="penroterneiras6mes")
    public Integer getPenroterneiras6mes() {
        return this.penroterneiras6mes;
    }
    
    public void setPenroterneiras6mes(Integer penroterneiras6mes) {
        this.penroterneiras6mes = penroterneiras6mes;
    }

    
    @Column(name="pevalortotal", precision=15)
    public BigDecimal getPevalortotal() {
        return this.pevalortotal;
    }
    
    public void setPevalortotal(BigDecimal pevalortotal) {
        this.pevalortotal = pevalortotal;
    }

    
    @Column(name="peobs")
    public String getPeobs() {
        return this.peobs;
    }
    
    public void setPeobs(String peobs) {
        this.peobs = peobs;
    }

    
    @Column(name="pecancelado", length=1)
    public String getPecancelado() {
        return this.pecancelado;
    }
    
    public void setPecancelado(String pecancelado) {
        this.pecancelado = pecancelado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pedataatu", nullable=false, length=13)
    public Date getPedataatu() {
        return this.pedataatu;
    }
    
    public void setPedataatu(Date pedataatu) {
        this.pedataatu = pedataatu;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="pehoraatu", nullable=false, length=15)
    public Date getPehoraatu() {
        return this.pehoraatu;
    }
    
    public void setPehoraatu(Date pehoraatu) {
        this.pehoraatu = pehoraatu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pedata", length=13)
    public Date getPedata() {
        return this.pedata;
    }
    
    public void setPedata(Date pedata) {
        this.pedata = pedata;
    }

    
    @Column(name="pemotivocancelamento")
    public String getPemotivocancelamento() {
        return this.pemotivocancelamento;
    }
    
    public void setPemotivocancelamento(String pemotivocancelamento) {
        this.pemotivocancelamento = pemotivocancelamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedidos")
    public Set<Itenspedido> getItenspedidos() {
        return this.itenspedidos;
    }
    
    public void setItenspedidos(Set<Itenspedido> itenspedidos) {
        this.itenspedidos = itenspedidos;
    }




}


