package classes;
// Generated 06/07/2017 22:21:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private ProdutosId id;
     private Empresa empresa;
     private String prnome;
     private Integer prgrupo;
     private String prunidade;
     private String prinativo;
     private Date prdataatu;
     private Date prhoraatu;

    public Produtos() {
    }

	
    public Produtos(ProdutosId id, Empresa empresa, Date prdataatu, Date prhoraatu) {
        this.id = id;
        this.empresa = empresa;
        this.prdataatu = prdataatu;
        this.prhoraatu = prhoraatu;
    }
    public Produtos(ProdutosId id, Empresa empresa, String prnome, Integer prgrupo, String prunidade, String prinativo, Date prdataatu, Date prhoraatu) {
       this.id = id;
       this.empresa = empresa;
       this.prnome = prnome;
       this.prgrupo = prgrupo;
       this.prunidade = prunidade;
       this.prinativo = prinativo;
       this.prdataatu = prdataatu;
       this.prhoraatu = prhoraatu;
    }
   
    public ProdutosId getId() {
        return this.id;
    }
    
    public void setId(ProdutosId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getPrnome() {
        return this.prnome;
    }
    
    public void setPrnome(String prnome) {
        this.prnome = prnome;
    }
    public Integer getPrgrupo() {
        return this.prgrupo;
    }
    
    public void setPrgrupo(Integer prgrupo) {
        this.prgrupo = prgrupo;
    }
    public String getPrunidade() {
        return this.prunidade;
    }
    
    public void setPrunidade(String prunidade) {
        this.prunidade = prunidade;
    }
    public String getPrinativo() {
        return this.prinativo;
    }
    
    public void setPrinativo(String prinativo) {
        this.prinativo = prinativo;
    }
    public Date getPrdataatu() {
        return this.prdataatu;
    }
    
    public void setPrdataatu(Date prdataatu) {
        this.prdataatu = prdataatu;
    }
    public Date getPrhoraatu() {
        return this.prhoraatu;
    }
    
    public void setPrhoraatu(Date prhoraatu) {
        this.prhoraatu = prhoraatu;
    }




}


