package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutosId generated by hbm2java
 */
@Embeddable
public class ProdutosId  implements java.io.Serializable {


     private int prempresa;
     private int prcodigo;

    public ProdutosId() {
    }

    public ProdutosId(int prempresa, int prcodigo) {
       this.prempresa = prempresa;
       this.prcodigo = prcodigo;
    }
   


    @Column(name="prempresa", nullable=false)
    public int getPrempresa() {
        return this.prempresa;
    }
    
    public void setPrempresa(int prempresa) {
        this.prempresa = prempresa;
    }


    @Column(name="prcodigo", nullable=false)
    public int getPrcodigo() {
        return this.prcodigo;
    }
    
    public void setPrcodigo(int prcodigo) {
        this.prcodigo = prcodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutosId) ) return false;
		 ProdutosId castOther = ( ProdutosId ) other; 
         
		 return (this.getPrempresa()==castOther.getPrempresa())
 && (this.getPrcodigo()==castOther.getPrcodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPrempresa();
         result = 37 * result + this.getPrcodigo();
         return result;
   }   


}


