package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,schema="public"
)
public class Produtos  implements java.io.Serializable {

     private ProdutosId id;
     private Empresa empresa;
     private Grupos grupos;
     private String prnome;
     private String prunidade;
     private String prinativo;
     private Date prdataatu;
     private Date prhoraatu;
     private Set<Tabelaprecosdetalhes> tabelaprecosdetalheses = new HashSet<Tabelaprecosdetalhes>(0);
     
    public Produtos() {
    }
	
    public Produtos(ProdutosId id, Empresa empresa, Grupos grupos, Date prdataatu, Date prhoraatu) {
        this.id = id;
        this.empresa = empresa;
        this.grupos = grupos;
        this.prdataatu = prdataatu;
        this.prhoraatu = prhoraatu;
    }
    public Produtos(ProdutosId id, Empresa empresa, Grupos grupos, String prnome, String prunidade, String prinativo, Date prdataatu, Date prhoraatu, Set<Tabelaprecosdetalhes> tabelaprecosdetalheses) {
       this.id = id;
       this.empresa = empresa;
       this.grupos = grupos;
       this.prnome = prnome;
       this.prunidade = prunidade;
       this.prinativo = prinativo;
       this.prdataatu = prdataatu;
       this.prhoraatu = prhoraatu;
       this.tabelaprecosdetalheses = tabelaprecosdetalheses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="prempresa", column=@Column(name="prempresa", nullable=false) ), 
        @AttributeOverride(name="prcodigo", column=@Column(name="prcodigo", nullable=false) ) } )
    public ProdutosId getId() {
        return this.id;
    }
    
    public void setId(ProdutosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prempresa", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="prgrupo", referencedColumnName="grempresa", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="prempresa", referencedColumnName="grcodigo", nullable=false, insertable=false, updatable=false) } )
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }

    
    @Column(name="prnome", length=100)
    public String getPrnome() {
        return this.prnome;
    }
    
    public void setPrnome(String prnome) {
        this.prnome = prnome;
    }

    
    @Column(name="prunidade", length=2)
    public String getPrunidade() {
        return this.prunidade;
    }
    
    public void setPrunidade(String prunidade) {
        this.prunidade = prunidade;
    }

    
    @Column(name="prinativo", length=1)
    public String getPrinativo() {
        return this.prinativo;
    }
    
    public void setPrinativo(String prinativo) {
        this.prinativo = prinativo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="prdataatu", nullable=false, length=13)
    public Date getPrdataatu() {
        return this.prdataatu;
    }
    
    public void setPrdataatu(Date prdataatu) {
        this.prdataatu = prdataatu;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="prhoraatu", nullable=false, length=15)
    public Date getPrhoraatu() {
        return this.prhoraatu;
    }
    
    public void setPrhoraatu(Date prhoraatu) {
        this.prhoraatu = prhoraatu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produtos")
    public Set<Tabelaprecosdetalhes> getTabelaprecosdetalheses() {
        return this.tabelaprecosdetalheses;
    }
    
    public void setTabelaprecosdetalheses(Set<Tabelaprecosdetalhes> tabelaprecosdetalheses) {
        this.tabelaprecosdetalheses = tabelaprecosdetalheses;
    }

    public void setGrupos(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


