package classes;
// Generated 27/06/2017 20:29:37 by Hibernate Tools 4.3.1



/**
 * Sequences generated by hbm2java
 */
public class Sequences  implements java.io.Serializable {


     private int secodigo;
     private Integer genempresa;
     private Integer genusuario;
     private Integer genclientes;
     private Integer genpedidos;
     private Integer gengrupos;
     private Integer genprodutos;
     private Integer genformaspgto;
     private Integer gentabelaprecos;

    public Sequences() {
    }

	
    public Sequences(int secodigo) {
        this.secodigo = secodigo;
    }
    public Sequences(int secodigo, Integer genempresa, Integer genusuario, Integer genclientes, Integer genpedidos, Integer gengrupos, Integer genprodutos, Integer genformaspgto, Integer gentabelaprecos) {
       this.secodigo = secodigo;
       this.genempresa = genempresa;
       this.genusuario = genusuario;
       this.genclientes = genclientes;
       this.genpedidos = genpedidos;
       this.gengrupos = gengrupos;
       this.genprodutos = genprodutos;
       this.genformaspgto = genformaspgto;
       this.gentabelaprecos = gentabelaprecos;
    }
   
    public int getSecodigo() {
        return this.secodigo;
    }
    
    public void setSecodigo(int secodigo) {
        this.secodigo = secodigo;
    }
    public Integer getGenempresa() {
        return this.genempresa;
    }
    
    public void setGenempresa(Integer genempresa) {
        this.genempresa = genempresa;
    }
    public Integer getGenusuario() {
        return this.genusuario;
    }
    
    public void setGenusuario(Integer genusuario) {
        this.genusuario = genusuario;
    }
    public Integer getGenclientes() {
        return this.genclientes;
    }
    
    public void setGenclientes(Integer genclientes) {
        this.genclientes = genclientes;
    }
    public Integer getGenpedidos() {
        return this.genpedidos;
    }
    
    public void setGenpedidos(Integer genpedidos) {
        this.genpedidos = genpedidos;
    }
    public Integer getGengrupos() {
        return this.gengrupos;
    }
    
    public void setGengrupos(Integer gengrupos) {
        this.gengrupos = gengrupos;
    }
    public Integer getGenprodutos() {
        return this.genprodutos;
    }
    
    public void setGenprodutos(Integer genprodutos) {
        this.genprodutos = genprodutos;
    }
    public Integer getGenformaspgto() {
        return this.genformaspgto;
    }
    
    public void setGenformaspgto(Integer genformaspgto) {
        this.genformaspgto = genformaspgto;
    }
    public Integer getGentabelaprecos() {
        return this.gentabelaprecos;
    }
    
    public void setGentabelaprecos(Integer gentabelaprecos) {
        this.gentabelaprecos = gentabelaprecos;
    }




}


