package classes;
// Generated 06/07/2017 22:21:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tabelaprecosdetalhes generated by hbm2java
 */
public class Tabelaprecosdetalhes  implements java.io.Serializable {


     private TabelaprecosdetalhesId id;
     private BigDecimal tdpreco;

    public Tabelaprecosdetalhes() {
    }

    public Tabelaprecosdetalhes(TabelaprecosdetalhesId id, BigDecimal tdpreco) {
       this.id = id;
       this.tdpreco = tdpreco;
    }
   
    public TabelaprecosdetalhesId getId() {
        return this.id;
    }
    
    public void setId(TabelaprecosdetalhesId id) {
        this.id = id;
    }
    public BigDecimal getTdpreco() {
        return this.tdpreco;
    }
    
    public void setTdpreco(BigDecimal tdpreco) {
        this.tdpreco = tdpreco;
    }




}


