package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tabelaprecosdetalhes generated by hbm2java
 */
@Entity
@Table(name="tabelaprecosdetalhes"
    ,schema="public"
)
public class Tabelaprecosdetalhes  implements java.io.Serializable {


     private TabelaprecosdetalhesId id;
     private Produtos produtos;
     private Tabelaprecos tabelaprecos;
     private BigDecimal tdpreco;
     private Set<Itenspedido> itenspedidos = new HashSet<Itenspedido>(0);

    public Tabelaprecosdetalhes() {
    }

	
    public Tabelaprecosdetalhes(TabelaprecosdetalhesId id, Produtos produtos, Tabelaprecos tabelaprecos, BigDecimal tdpreco) {
        this.id = id;
        this.produtos = produtos;
        this.tabelaprecos = tabelaprecos;
        this.tdpreco = tdpreco;
    }
    public Tabelaprecosdetalhes(TabelaprecosdetalhesId id, Produtos produtos, Tabelaprecos tabelaprecos, BigDecimal tdpreco, Set<Itenspedido> itenspedidos) {
       this.id = id;
       this.produtos = produtos;
       this.tabelaprecos = tabelaprecos;
       this.tdpreco = tdpreco;
       this.itenspedidos = itenspedidos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tdempresa", column=@Column(name="tdempresa", nullable=false) ), 
        @AttributeOverride(name="tdtabelapreco", column=@Column(name="tdtabelapreco", nullable=false) ), 
        @AttributeOverride(name="tdproduto", column=@Column(name="tdproduto", nullable=false) ) } )
    public TabelaprecosdetalhesId getId() {
        return this.id;
    }
    
    public void setId(TabelaprecosdetalhesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="tdproduto", referencedColumnName="prempresa", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="tdempresa", referencedColumnName="prcodigo", nullable=false, insertable=false, updatable=false) } )
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="tdempresa", referencedColumnName="tpempresa", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="tdtabelapreco", referencedColumnName="tpcodigo", nullable=false, insertable=false, updatable=false) } )
    public Tabelaprecos getTabelaprecos() {
        return this.tabelaprecos;
    }
    
    public void setTabelaprecos(Tabelaprecos tabelaprecos) {
        this.tabelaprecos = tabelaprecos;
    }

    
    @Column(name="tdpreco", nullable=false, precision=15)
    public BigDecimal getTdpreco() {
        return this.tdpreco;
    }
    
    public void setTdpreco(BigDecimal tdpreco) {
        this.tdpreco = tdpreco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tabelaprecosdetalhes")
    public Set<Itenspedido> getItenspedidos() {
        return this.itenspedidos;
    }
    
    public void setItenspedidos(Set<Itenspedido> itenspedidos) {
        this.itenspedidos = itenspedidos;
    }




}


