package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TabelaprecosdetalhesId generated by hbm2java
 */
@Embeddable
public class TabelaprecosdetalhesId  implements java.io.Serializable {


     private int tdempresa;
     private int tdtabelapreco;
     private int tdproduto;

    public TabelaprecosdetalhesId() {
    }

    public TabelaprecosdetalhesId(int tdempresa, int tdtabelapreco, int tdproduto) {
       this.tdempresa = tdempresa;
       this.tdtabelapreco = tdtabelapreco;
       this.tdproduto = tdproduto;
    }
   


    @Column(name="tdempresa", nullable=false)
    public int getTdempresa() {
        return this.tdempresa;
    }
    
    public void setTdempresa(int tdempresa) {
        this.tdempresa = tdempresa;
    }


    @Column(name="tdtabelapreco", nullable=false)
    public int getTdtabelapreco() {
        return this.tdtabelapreco;
    }
    
    public void setTdtabelapreco(int tdtabelapreco) {
        this.tdtabelapreco = tdtabelapreco;
    }


    @Column(name="tdproduto", nullable=false)
    public int getTdproduto() {
        return this.tdproduto;
    }
    
    public void setTdproduto(int tdproduto) {
        this.tdproduto = tdproduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TabelaprecosdetalhesId) ) return false;
		 TabelaprecosdetalhesId castOther = ( TabelaprecosdetalhesId ) other; 
         
		 return (this.getTdempresa()==castOther.getTdempresa())
 && (this.getTdtabelapreco()==castOther.getTdtabelapreco())
 && (this.getTdproduto()==castOther.getTdproduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTdempresa();
         result = 37 * result + this.getTdtabelapreco();
         result = 37 * result + this.getTdproduto();
         return result;
   }   


}


