package classes;
// Generated 06/07/2017 22:21:10 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Empresa empresa;
     private String usnome;
     private String ususuario;
     private String ussenha;
     private String ustipoacesso;

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Empresa empresa, String ususuario) {
        this.id = id;
        this.empresa = empresa;
        this.ususuario = ususuario;
    }
    public Usuario(UsuarioId id, Empresa empresa, String usnome, String ususuario, String ussenha, String ustipoacesso) {
       this.id = id;
       this.empresa = empresa;
       this.usnome = usnome;
       this.ususuario = ususuario;
       this.ussenha = ussenha;
       this.ustipoacesso = ustipoacesso;
    }
   
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getUsnome() {
        return this.usnome;
    }
    
    public void setUsnome(String usnome) {
        this.usnome = usnome;
    }
    public String getUsusuario() {
        return this.ususuario;
    }
    
    public void setUsusuario(String ususuario) {
        this.ususuario = ususuario;
    }
    public String getUssenha() {
        return this.ussenha;
    }
    
    public void setUssenha(String ussenha) {
        this.ussenha = ussenha;
    }
    public String getUstipoacesso() {
        return this.ustipoacesso;
    }
    
    public void setUstipoacesso(String ustipoacesso) {
        this.ustipoacesso = ustipoacesso;
    }




}


