package classes;
// Generated 27/06/2017 20:29:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Empresa empresa;
     private String usnome;
     private String uscpf;
     private String uscnpj;
     private String uscep;
     private String usuf;
     private String usbairro;
     private String uscidade;
     private String usendereco;
     private String usemail;
     private String ustelefone;
     private String ussenhamd5;
     private String ustipoacesso;
     private Set pedidoses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Empresa empresa, String usendereco, String usemail) {
        this.id = id;
        this.empresa = empresa;
        this.usendereco = usendereco;
        this.usemail = usemail;
    }
    public Usuario(UsuarioId id, Empresa empresa, String usnome, String uscpf, String uscnpj, String uscep, String usuf, String usbairro, String uscidade, String usendereco, String usemail, String ustelefone, String ussenhamd5, String ustipoacesso, Set pedidoses) {
       this.id = id;
       this.empresa = empresa;
       this.usnome = usnome;
       this.uscpf = uscpf;
       this.uscnpj = uscnpj;
       this.uscep = uscep;
       this.usuf = usuf;
       this.usbairro = usbairro;
       this.uscidade = uscidade;
       this.usendereco = usendereco;
       this.usemail = usemail;
       this.ustelefone = ustelefone;
       this.ussenhamd5 = ussenhamd5;
       this.ustipoacesso = ustipoacesso;
       this.pedidoses = pedidoses;
    }
   
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getUsnome() {
        return this.usnome;
    }
    
    public void setUsnome(String usnome) {
        this.usnome = usnome;
    }
    public String getUscpf() {
        return this.uscpf;
    }
    
    public void setUscpf(String uscpf) {
        this.uscpf = uscpf;
    }
    public String getUscnpj() {
        return this.uscnpj;
    }
    
    public void setUscnpj(String uscnpj) {
        this.uscnpj = uscnpj;
    }
    public String getUscep() {
        return this.uscep;
    }
    
    public void setUscep(String uscep) {
        this.uscep = uscep;
    }
    public String getUsuf() {
        return this.usuf;
    }
    
    public void setUsuf(String usuf) {
        this.usuf = usuf;
    }
    public String getUsbairro() {
        return this.usbairro;
    }
    
    public void setUsbairro(String usbairro) {
        this.usbairro = usbairro;
    }
    public String getUscidade() {
        return this.uscidade;
    }
    
    public void setUscidade(String uscidade) {
        this.uscidade = uscidade;
    }
    public String getUsendereco() {
        return this.usendereco;
    }
    
    public void setUsendereco(String usendereco) {
        this.usendereco = usendereco;
    }
    public String getUsemail() {
        return this.usemail;
    }
    
    public void setUsemail(String usemail) {
        this.usemail = usemail;
    }
    public String getUstelefone() {
        return this.ustelefone;
    }
    
    public void setUstelefone(String ustelefone) {
        this.ustelefone = ustelefone;
    }
    public String getUssenhamd5() {
        return this.ussenhamd5;
    }
    
    public void setUssenhamd5(String ussenhamd5) {
        this.ussenhamd5 = ussenhamd5;
    }
    public String getUstipoacesso() {
        return this.ustipoacesso;
    }
    
    public void setUstipoacesso(String ustipoacesso) {
        this.ustipoacesso = ustipoacesso;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


