package classes;
// Generated 18/06/2017 19:11:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Empresa empresa;
     private String usnome;
     private String uscpf;
     private String uscnpj;
     private String uscep;
     private String usuf;
     private String usbairro;
     private String uscidade;
     private String usendereco;
     private String usemail;
     private String ustelefone;
     private String ussenhamd5;
     private String ustipoacesso;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Empresa empresa, String usendereco, String usemail) {
        this.id = id;
        this.empresa = empresa;
        this.usendereco = usendereco;
        this.usemail = usemail;
    }
    public Usuario(UsuarioId id, Empresa empresa, String usnome, String uscpf, String uscnpj, String uscep, String usuf, String usbairro, String uscidade, String usendereco, String usemail, String ustelefone, String ussenhamd5, String ustipoacesso, Set<Pedidos> pedidoses) {
       this.id = id;
       this.empresa = empresa;
       this.usnome = usnome;
       this.uscpf = uscpf;
       this.uscnpj = uscnpj;
       this.uscep = uscep;
       this.usuf = usuf;
       this.usbairro = usbairro;
       this.uscidade = uscidade;
       this.usendereco = usendereco;
       this.usemail = usemail;
       this.ustelefone = ustelefone;
       this.ussenhamd5 = ussenhamd5;
       this.ustipoacesso = ustipoacesso;
       this.pedidoses = pedidoses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="uscodigo", column=@Column(name="uscodigo", nullable=false) ), 
        @AttributeOverride(name="usempresa", column=@Column(name="usempresa", nullable=false) ) } )
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usempresa", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="usnome", length=50)
    public String getUsnome() {
        return this.usnome;
    }
    
    public void setUsnome(String usnome) {
        this.usnome = usnome;
    }

    
    @Column(name="uscpf", length=11)
    public String getUscpf() {
        return this.uscpf;
    }
    
    public void setUscpf(String uscpf) {
        this.uscpf = uscpf;
    }

    
    @Column(name="uscnpj", length=14)
    public String getUscnpj() {
        return this.uscnpj;
    }
    
    public void setUscnpj(String uscnpj) {
        this.uscnpj = uscnpj;
    }

    
    @Column(name="uscep", length=9)
    public String getUscep() {
        return this.uscep;
    }
    
    public void setUscep(String uscep) {
        this.uscep = uscep;
    }

    
    @Column(name="usuf", length=2)
    public String getUsuf() {
        return this.usuf;
    }
    
    public void setUsuf(String usuf) {
        this.usuf = usuf;
    }

    
    @Column(name="usbairro", length=30)
    public String getUsbairro() {
        return this.usbairro;
    }
    
    public void setUsbairro(String usbairro) {
        this.usbairro = usbairro;
    }

    
    @Column(name="uscidade", length=50)
    public String getUscidade() {
        return this.uscidade;
    }
    
    public void setUscidade(String uscidade) {
        this.uscidade = uscidade;
    }

    
    @Column(name="usendereco", nullable=false, length=100)
    public String getUsendereco() {
        return this.usendereco;
    }
    
    public void setUsendereco(String usendereco) {
        this.usendereco = usendereco;
    }

    
    @Column(name="usemail", nullable=false, length=50)
    public String getUsemail() {
        return this.usemail;
    }
    
    public void setUsemail(String usemail) {
        this.usemail = usemail;
    }

    
    @Column(name="ustelefone", length=20)
    public String getUstelefone() {
        return this.ustelefone;
    }
    
    public void setUstelefone(String ustelefone) {
        this.ustelefone = ustelefone;
    }

    
    @Column(name="ussenhamd5", length=100)
    public String getUssenhamd5() {
        return this.ussenhamd5;
    }
    
    public void setUssenhamd5(String ussenhamd5) {
        this.ussenhamd5 = ussenhamd5;
    }

    
    @Column(name="ustipoacesso", length=10)
    public String getUstipoacesso() {
        return this.ustipoacesso;
    }
    
    public void setUstipoacesso(String ustipoacesso) {
        this.ustipoacesso = ustipoacesso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }




}


